### PR TITLE
Chore: created FileHandler class

### PR DESCRIPTION
**Pull request by xervir**
Does anyone know how to fix a typo in the commit summary after you've already pushed it? Because that's an annoying one, but if I had to delete the branch to fix it it's not worth it.

### CODE REVIEW

**Comment by cclinard84** [comment]
if you do a `git rebase -i HEAD~1` it will go to your last commit. You can then reword your commit that way when you get the opportunity to change your commit history.

**Comment by cclinard84** [comment]
By the way, you will then have to force push to your branch `git push -f` to force push those changes.

**Comment by xervir** [comment]
Okay, thank you. I'll do that.
Does the content look okay, though?

**Comment by cclinard84** [comment]
Haven't looked at it yet since I am at work but I will take a gander when I get home tonight. Glad to see you got the line endings thing sorted out 👍

**Comment by fdlane** [comment]
Great work guys.

**Pull request closed without merging**
